export default fonts = {
  subHeadUser: {
    fontFamily: 'Urbanist-Regular',
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 20,
  },
  ResultHead: {
    fontFamily: 'Urbanist-SemiBold',
    fontWeight: '600',
    fontSize: 15,
    lineHeight: 26,
  },
  topNav: {
    fontFamily: 'Urbanist-Regular',
    fontWeight: '600',
    fontSize: 12,
    lineHeight: 24,
  },
  ResultHead2: {
    fontFamily: 'Urbanist-Regular',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 24,
    fontStyle: 'normal',
  },
  timer: {
    fontFamily: 'Urbanist-Regular',
    fontWeight: '600',
    fontSize: 48,
    lineHeight: 24,
  },
  subHeadUser3: {
    fontFamily: 'Urbanist-Regular',
    fontWeight: '600',
    fontSize: 18,
    lineHeight: 26,
  },
  subHeadUser2: {
    fontFamily: 'Urbanist-SemiBold',
    fontWeight: '600',
    fontSize: 20,
    lineHeight: 26,
    fontFamily: 'normal',
  },
  result: {
    fontFamily: 'Urbanist-Regular',
    fontWeight: '600',
    fontSize: 15,
    lineHeight: 26,
  },
  toggle: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    lineHeight: 14.8,
  },
  symptoms: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    lineHeight: 20,
  },
  date: {
    fontFamily: 'Urbanist-Regular',
    fontWeight: '700',
    fontSize: 16,
    lineHeight: 24,
  },
  log: {
    fontFamily: 'Urbanist-Regular',
    fontWeight: '600',
    fontSize: 24,
    lineHeight: 26,
  },
  dashboardMain: {
    fontFamily: 'Poppins-Regular',
    fontWeight: '500',
    fontSize: 30,
  },
  dashboardSubHead: {
    fontFamily: 'Poppins-Regular',
    fontSize: 13,
    lineHeight: 24,
  },
  subItems: {
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    lineHeight: 18,
  },
  mainHeading: {
    fontFamily: 'Poppins-Regular',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 24,
    lineHeight: 36,
  },
  items: {
    fontFamily: 'Poppins-Regular',
    fontWeight: 'bold',
    fontSize: 14,
    fontStyle: 'normal',
  },
  itemCount: {
    fontFamily: 'Poppins-Regular',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 21,
  },
  inputHead: {
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
  },
  button: {
    fontFamily: 'Inter-Regular',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 2,
  },
  tittle: {
    fontFamily: 'Poppins-Regular',
    fontSize: 24,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: 0.48,
  },
  subTitle: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 24,
    letterSpacing: 0.28,
  },
  password: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 24,
  },
  signInWith: {
    fontFamily: 'Inter-Regular',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '400',
    letterSpacing: 0.36,
  },
  signIn: {
    fontFamily: 'Inter-Regular',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: 24,
    letterSpacing: 0.32,
  },
  socialText: {
    fontFamily: 'Inter-Regular',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: 24,
    letterSpacing: 0.28,
  },
  signUp: {
    fontFamily: 'Inter-Regular',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 24,
  },
  forgetPasswordSubTitle: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 24,
  },
  sendEmail: {
    fontFamily: 'Urbanist-Regular',
    fontWeight: '600',
    fontSize: 18,
    fontStyle: 'normal',
    lineHeight: 26,
  },
  resendText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 24,
  },
  accCreatedTitle: {
    fontFamily: 'Manrope-Regular',
    fontSize: 28,
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: 38,
    letterSpacing: -0.28,
  },
  accCreatedSubTitle: {
    fontFamily: 'Manrope-Regular',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 24,
    letterSpacing: -0.14,
  },
  account: {
    fontFamily: 'Urbanist-Regular',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: 24,
  },
  feedBack: {
    fontFamily: 'Poppins-Regular',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '500',
    letterSpacing: 0.3,
  },
  attendance: {
    fontFamily: 'Urbanist-Regular',
    fontWeight: '600',
    fontSize: 48,
    fontStyle: 'normal',
  },
  attendanceSub: {
    fontFamily: 'Urbanist-Regular',
    fontWeight: '600',
    fontSize: 20,
    fontStyle: 'normal',
    lineHeight: 24,
  },
  annoucement: {
    fontFamily: 'Roboto-Regular',
    fontWeight: '700',
    fontSize: 20,
  },
  annoucementText: {
    fontFamily: 'Roboto-Regular',
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 20,
  },
  annoucementTimer: {
    fontFamily: 'Roboto-Regular',
    fontWeight: '500',
    fontSize: 12,
  },
  annoucementText1: {
    fontFamily: 'Roboto-Regular',
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 20,
  },
  annoucementDescription: {
    fontFamily: 'Urbanist-Regular',
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 26,
  },
  counter: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '600',
  },
  modalItemName: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    lineHeight: 24,
    fontStyle: 'normal',
    fontWeight: '600',
  },
  modalItemDesc: {
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    lineHeight: 18,
    fontStyle: 'normal',
    fontWeight: '400',
  },
  modalItemQty: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    lineHeight: 21,
    fontStyle: 'normal',
    fontWeight: '500',
  },
  modalHeading: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 18,
    lineHeight: 26,
    fontStyle: 'normal',
    fontWeight: '600',
  },
  totalKcalCount: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    lineHeight: 21,
    fontStyle: 'normal',
    fontWeight: '600',
  },
};
